name: Terraform apply
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths: 'terraform/**'

env:
  AWS_REGION:  "eu-west-2"
  S3_BUCKET_NAME: "cloud-platform-36623f774b9641d8697d65bdf6b030f5"
  DYNAMODB_TABLE: "cp-b6970ba60ed66537"
  TERRAFORM: terraform
  AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_github_token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
  TF_IN_AUTOMATION: true

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.11
      - run: |
          cd terraform
          terraform init -backend-config="bucket=${S3_BUCKET_NAME}" -backend-config="dynamodb_table=${DYNAMODB_TABLE}"
          terraform apply -auto-approve
      - name: Update OpsEng collaborators report
        run: bin/post-data.sh
        env:
          ADMIN_GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          OPERATIONS_ENGINEERING_REPORTS_API_KEY: ${{ secrets.OPERATIONS_ENGINEERING_REPORTS_API_KEY }}
          OPERATIONS_ENGINEERING_REPORTS_HOST: ${{ secrets.OPERATIONS_ENGINEERING_REPORTS_HOST }}
          OPS_ENG_REPORTS_URL: ${{ secrets.OPERATIONS_ENGINEERING_REPORTS_HOST }}/github_collaborators
